let EventModel = {
  ON_SPEECH_RECOGNITION_RESULT: 'ON_SPEECH_RECOGNITION_RESULT',
  ON_CHECK_SKILL: 'ON_CHECK_SKILL',
  HAS_SKILL_CHECK: 'HAS_SKILL_CHECK',
  SEND_RESPONSE: 'SEND_RESPONSE',
  STOP_SKILL: 'STOP_SKILL',
  RESUME_LISTENING: 'RESUME_LISTENING',
  STOP_LISTENING: 'STOP_LISTENING',
  GREETING: 'GREETING',
  SPEAK: 'SPEAK'
};

export default EventModel;