let EventModel = {
  ON_CHECK_SKILL: 'ON_CHECK_SKILL',
  HAS_SKILL_CHECK: 'HAS_SKILL_CHECK',
  STOP_SKILL: 'STOP_SKILL',
  RESUME_LISTENING: 'RESUME_LISTENING',
  STOP_LISTENING: 'STOP_LISTENING',
  TRIGGERED_GREETING: 'TRIGGERED_GREETING',
  SPEAK: 'SPEAK',
  UPDATE_CONTEXT: 'UPDATE_CONTEXT'
};

export default EventModel;
